// GENERATED by scripts/extract-theme-colors.js — do not edit.
// Regenerate with `pnpm gen:theme-colors` after changing a theme's colors.
// Values are read from each theme's own CSS so a preview swatch cannot drift
// from what the theme actually paints.

export interface ThemeColors {
	readonly bg: string;
	readonly text: string;
	readonly accent: string;
}

export const themeColors = {
	"arctic-ice": { bg: "#f0f7ff", text: "#1e3a5f", accent: "#0284c7" },
	"art-deco": { bg: "#1a1a2e", text: "#f0e6d3", accent: "#d4af37" },
	"candy-pop": { bg: "#fffbfe", text: "#4a2153", accent: "#ff6b9d" },
	"cosmic-purple": { bg: "#0f0720", text: "#e8dff5", accent: "#c084fc" },
	"electric-blue": { bg: "#0c1222", text: "#c8d6e5", accent: "#3b82f6" },
	"forest-earth": { bg: "#f5f0e8", text: "#2d3a2e", accent: "#4a7c59" },
	"github-dark": { bg: "#0d1117", text: "#e6edf3", accent: "#58a6ff" },
	"github-light": { bg: "#ffffff", text: "#1f2328", accent: "#0969da" },
	"glassmorphism": { bg: "#667eea", text: "#f0f0f0", accent: "#a8d8ff" },
	"handwritten": { bg: "#fffff8", text: "#333333", accent: "#2980b9" },
	"ink-brush": { bg: "#faf8f5", text: "#2c2c2c", accent: "#c62828" },
	"minimal-mono": { bg: "#fafafa", text: "#1a1a1a", accent: "#0066ff" },
	"neo-brutalist": { bg: "#fffdf0", text: "#1a1a1a", accent: "#ff5722" },
	"neon-cyberpunk": { bg: "#0a0014", text: "#e0d4ff", accent: "#ff00ff" },
	"newspaper": { bg: "#fdf8ef", text: "#222222", accent: "#8b0000" },
	"pastel-dream": { bg: "#fef9ff", text: "#4a3f6b", accent: "#b388ff" },
	"retro-terminal": { bg: "#0a0a0a", text: "#00ff41", accent: "#00ff41" },
	"sunset-desert": { bg: "#fef7ed", text: "#5c3d2e", accent: "#e07a5f" },
	"swiss-design": { bg: "#ffffff", text: "#111111", accent: "#ff0000" },
	"tropical-sunset": { bg: "#fff7ed", text: "#4a2c17", accent: "#f97316" },
	"vaporwave": { bg: "#2d1b69", text: "#e8c4f0", accent: "#ff71ce" },
	"warm-paper": { bg: "#fdf6ec", text: "#3d3229", accent: "#c0392b" },
} as const satisfies Record<string, ThemeColors>;

export type ThemeColorId = keyof typeof themeColors;
