// GENERATED by scripts/extract-theme-colors.ts — do not edit.
// Regenerate with `pnpm gen:theme-colors` after changing a theme's colors.
// Values are read from each theme's own CSS so a preview swatch cannot drift
// from what the theme actually paints.

export interface ThemeColors {
	readonly bg: string;
	readonly text: string;
	readonly accent: string;
}

export const themeColors = {
	"candy-pop": { bg: "#fffbfe", text: "#4a2153", accent: "#ff6b9d" },
	"github-dark": { bg: "#0d1117", text: "#e6edf3", accent: "#58a6ff" },
	"github-light": { bg: "#ffffff", text: "#1f2328", accent: "#0969da" },
	"minimal-mono": { bg: "#fafafa", text: "#1a1a1a", accent: "#0066ff" },
	"neo-brutalist": { bg: "#fffdf0", text: "#1a1a1a", accent: "#ff5722" },
	"pastel-dream": { bg: "#fef9ff", text: "#4a3f6b", accent: "#b388ff" },
	"swiss-design": { bg: "#ffffff", text: "#111111", accent: "#ff0000" },
} as const satisfies Record<string, ThemeColors>;

export type ThemeColorId = keyof typeof themeColors;
