// GENERATED by scripts/extract-theme-colors.ts — do not edit.
// Regenerate with `pnpm gen:theme-colors` after changing a theme's frontmatter.
// Values are read from each theme's own `/*! @name … @description … @author … */`
// frontmatter block so display metadata cannot drift from the CSS file itself.

export interface ThemeMetaEntry {
	readonly name: string;
	readonly description: string;
	readonly author: string;
}

export const themeMeta = {
	"arctic-ice": { name: "Arctic Ice", description: "Pale ice-blue background with a cool navy-blue text color and sky-blue accent.", author: "peep" },
	"art-deco": { name: "Art Deco", description: "Midnight navy background with gold-foil accents, centered small-caps Playfair Display headings, and diamond glyph dividers.", author: "peep" },
	"candy-pop": { name: "Candy Pop", description: "Bright white background with a five-color gradient-clipped h1 and dashed yellow rule under h2.", author: "peep" },
	"cosmic-purple": { name: "Cosmic Purple", description: "Deep space-purple background with a radial nebula glow and text-shadow halos on violet and pink headings.", author: "peep" },
	"electric-blue": { name: "Electric Blue", description: "Near-black background in IBM Plex Mono with blue glow accents and a blue-shadowed monospace code block.", author: "peep" },
	"forest-earth": { name: "Forest & Earth", description: "Warm off-white background with mossy green and bark-brown headings on serif Merriweather body text.", author: "peep" },
	"github-dark": { name: "GitHub Dark", description: "GitHub's dark UI palette, token-only so every rule lives in base.css.", author: "peep" },
	"github-light": { name: "GitHub Light", description: "GitHub's light UI palette, token-only so every rule lives in base.css.", author: "peep" },
	"glassmorphism": { name: "Glassmorphism", description: "Frosted-glass panels over a purple gradient backdrop, built entirely from backdrop-filter blur and translucent fills.", author: "peep" },
	"handwritten": { name: "Handwritten", description: "Cream ruled-notebook background with cursive headings, wavy underlines, and a red margin rule.", author: "peep" },
	"ink-brush": { name: "Ink & Brush", description: "Cream paper with a red accent dot, serif Merriweather type, and understated East Asian brush-painting restraint.", author: "peep" },
	"minimal-mono": { name: "Minimal Mono", description: "Off-white background in IBM Plex Mono with literal Markdown hash marks rendered before each heading.", author: "peep" },
	"neo-brutalist": { name: "Neo Brutalist", description: "Thick black borders, hard drop shadows, and an h2 accent bar rendered as a calc()-derived hanging rule.", author: "peep" },
	"neon-cyberpunk": { name: "Neon Cyberpunk", description: "Near-black background with saturated pink and cyan glow, monospace headings lit by text-shadow.", author: "peep" },
	"newspaper": { name: "Newspaper", description: "Aged-paper background with a centered double-ruled Playfair Display masthead headline and Courier Prime for code.", author: "peep" },
	"pastel-dream": { name: "Pastel Dream", description: "Soft lavender background with a gradient-clipped h1 and pastel purple/pink accents.", author: "peep" },
	"retro-terminal": { name: "Retro Terminal", description: "Phosphor-green monospace text on black with scanline texture and glowing text-shadow headings.", author: "peep" },
	"sunset-desert": { name: "Sunset Desert", description: "Warm sandy background with terracotta and sage accents and wide-tracked uppercase h2.", author: "peep" },
	"swiss-design": { name: "Swiss Design", description: "Stark white background, oversized black display type, and a single red accent in International Typographic Style.", author: "peep" },
	"tropical-sunset": { name: "Tropical Sunset", description: "Warm peach-to-orange gradient background with a pink-to-orange gradient-clipped h1.", author: "peep" },
	"vaporwave": { name: "Vaporwave", description: "Purple-to-magenta gradient background with a subtle grid of near-transparent scanlines and neon pink/cyan headings.", author: "peep" },
	"warm-paper": { name: "Warm Paper", description: "Cream paper background with a dark-red accent and serif Merriweather body text.", author: "peep" },
} as const satisfies Record<string, ThemeMetaEntry>;

export type ThemeMetaId = keyof typeof themeMeta;
