// GENERATED by scripts/extract-theme-colors.ts — do not edit.
// Regenerate with `pnpm gen:theme-colors` after changing a theme's frontmatter.
// Values are read from each theme's own `/*! @name … @description … @author … */`
// frontmatter block so display metadata cannot drift from the CSS file itself.

export interface ThemeMetaEntry {
	readonly name: string;
	readonly description: string;
	readonly author: string;
}

export const themeMeta = {
	"candy-pop": { name: "Candy Pop", description: "Bright white background with a five-color gradient-clipped h1 and dashed yellow rule under h2.", author: "peep" },
	"github-dark": { name: "GitHub Dark", description: "GitHub's dark UI palette, token-only so every rule lives in base.css.", author: "peep" },
	"github-light": { name: "GitHub Light", description: "GitHub's light UI palette, token-only so every rule lives in base.css.", author: "peep" },
	"minimal-mono": { name: "Minimal Mono", description: "Off-white background in IBM Plex Mono with literal Markdown hash marks rendered before each heading.", author: "peep" },
	"neo-brutalist": { name: "Neo Brutalist", description: "Thick black borders, hard drop shadows, and an h2 accent bar rendered as a calc()-derived hanging rule.", author: "peep" },
	"pastel-dream": { name: "Pastel Dream", description: "Soft lavender background with a gradient-clipped h1 and pastel purple/pink accents.", author: "peep" },
	"swiss-design": { name: "Swiss Design", description: "Stark white background, oversized black display type, and a single red accent in International Typographic Style.", author: "peep" },
} as const satisfies Record<string, ThemeMetaEntry>;

export type ThemeMetaId = keyof typeof themeMeta;
