/**
 * Derives the palette swatches shown in the command palette and Preferences,
 * and the display metadata (name/description/author), from the theme CSS
 * itself, so neither can disagree with what the theme actually paints or
 * claims to be. Previously `registry.ts` hand-authored the three swatch hex
 * values next to a `load()` for a file that repeated them — nothing kept the
 * pair in sync, and a preview could silently lie about its theme.
 *
 * Run via `pnpm gen:theme-colors`; both generated files are committed so the
 * app and tests never depend on this script at runtime.
 *
 * Two theme shapes are supported for the swatch, because migration to tokens
 * is incremental:
 *   - token themes  → read --md-bg / --md-text / --md-accent
 *   - legacy themes → read background / color / --md-accent from the .app rule
 * Token lookups win, so a theme gets more direct as it migrates.
 *
 * `.ts` run directly by Node (v24's `process.features.typescript === "strip"`
 * erases the types with no build step, no new devDependency). The explicit
 * `.ts` extension on the parser import is required by Node's ESM resolver and
 * permitted by this project's `moduleResolution: "bundler"`, so svelte-check
 * and Vite accept the same specifier the runtime importer will use.
 *
 * The actual parsing lives in `src/lib/themes/parse-theme-css.ts` — shared
 * with the runtime user-theme importer so the two never drift apart. This
 * file only does the parts specific to the build: walking the themes
 * directory, using the throwing `assertParsed` adapter (a missing swatch or
 * frontmatter field for a *bundled* theme is a bug, not something to degrade
 * around), and writing the generated output files.
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { assertParsed } from "../src/lib/themes/parse-theme-css.ts";
import type { ParsedTheme } from "../src/lib/themes/parse-theme-css.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const THEMES_DIR = join(HERE, "..", "src", "lib", "themes", "themes");
const COLORS_OUT_FILE = join(HERE, "..", "src", "lib", "themes", "theme-colors.ts");
const META_OUT_FILE = join(HERE, "..", "src", "lib", "themes", "theme-meta.ts");

const files = readdirSync(THEMES_DIR)
	.filter((f) => f.endsWith(".css"))
	.sort();

const entries = files.map((file) => {
	const css = readFileSync(join(THEMES_DIR, file), "utf8");
	const parsed: ParsedTheme = assertParsed(css, file);
	return [file.replace(/\.css$/, ""), parsed] as const;
});

const colorsBody = entries
	.map(([id, t]) => `\t"${id}": { bg: "${t.swatch.bg}", text: "${t.swatch.text}", accent: "${t.swatch.accent}" },`)
	.join("\n");

const colorsOut = `// GENERATED by scripts/extract-theme-colors.ts — do not edit.
// Regenerate with \`pnpm gen:theme-colors\` after changing a theme's colors.
// Values are read from each theme's own CSS so a preview swatch cannot drift
// from what the theme actually paints.

export interface ThemeColors {
	readonly bg: string;
	readonly text: string;
	readonly accent: string;
}

export const themeColors = {
${colorsBody}
} as const satisfies Record<string, ThemeColors>;

export type ThemeColorId = keyof typeof themeColors;
`;

writeFileSync(COLORS_OUT_FILE, colorsOut);
console.log(`Wrote ${entries.length} theme palettes to ${COLORS_OUT_FILE}`);

// Escape a string for embedding in a double-quoted TS string literal. Author
// content is a fixed constant ("peep") but name/description come from
// frontmatter written by hand in this repo — still worth not trusting blindly,
// since a stray `"` or backslash in a future theme's description would
// otherwise emit invalid TypeScript.
function quote(value: string): string {
	return JSON.stringify(value);
}

const metaBody = entries
	.map(
		([id, t]) =>
			`\t"${id}": { name: ${quote(t.frontmatter.name)}, description: ${quote(t.frontmatter.description)}, author: ${quote(t.frontmatter.author)} },`,
	)
	.join("\n");

const metaOut = `// GENERATED by scripts/extract-theme-colors.ts — do not edit.
// Regenerate with \`pnpm gen:theme-colors\` after changing a theme's frontmatter.
// Values are read from each theme's own \`/*! @name … @description … @author … */\`
// frontmatter block so display metadata cannot drift from the CSS file itself.

export interface ThemeMetaEntry {
	readonly name: string;
	readonly description: string;
	readonly author: string;
}

export const themeMeta = {
${metaBody}
} as const satisfies Record<string, ThemeMetaEntry>;

export type ThemeMetaId = keyof typeof themeMeta;
`;

writeFileSync(META_OUT_FILE, metaOut);
console.log(`Wrote ${entries.length} theme metadata entries to ${META_OUT_FILE}`);
