/**
 * Generates `themes/README.md`, the browsable index for the repo-root theme
 * gallery. The gallery themes are shipped as CSS files a user imports, not
 * themes the app bundles — see `src/lib/themes/registry.ts`'s note on the
 * builtins vs. the gallery split (peep-rgm).
 *
 * Run via `pnpm gen:gallery-readme`. The output is committed and verified by
 * `src/lib/themes/gallery-readme.test.ts`, which rebuilds it from the same
 * `themes/*.css` files and asserts strict equality — so a hand-edited README,
 * an added/removed gallery theme, or an edited frontmatter block fails
 * `pnpm test` rather than silently drifting from what's actually on disk.
 *
 * Deliberately its own script, not an extension of `extract-theme-colors.ts`:
 * that script produces committed TypeScript modules the app imports at
 * runtime; this one produces a human-facing Markdown file for a directory the
 * app never reads. Different contract, different output tree.
 *
 * `.ts` run directly by Node (v24's `process.features.typescript === "strip"`
 * erases the types with no build step). The explicit `.ts` extension on the
 * parser import is required by Node's ESM resolver and permitted by this
 * project's `moduleResolution: "bundler"`, so svelte-check and Vite accept the
 * same specifier the runtime importer will use.
 *
 * The throwing `assertParsed` adapter is correct here, same as in
 * `extract-theme-colors.ts`: every file under `themes/` is our own, so a
 * malformed one is a bug to fail loudly on, not user input to degrade around.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { assertParsed } from "../src/lib/themes/parse-theme-css.ts";
import type { ParsedTheme } from "../src/lib/themes/parse-theme-css.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const GALLERY_DIR = join(HERE, "..", "themes");
const README_OUT_FILE = join(GALLERY_DIR, "README.md");

/**
 * Where `scripts/theme-shots.mjs` writes its PNGs, expressed RELATIVE TO
 * `themes/README.md` — that is the file these links are resolved from, not the
 * repo root. Screenshots are generated by a separate command on purpose: this
 * generator is pure and runs in milliseconds, while the screenshot harness
 * boots Chromium and bundles shiki. Coupling them would put a browser launch
 * behind `pnpm test`, which imports this module.
 */
const SHOTS_REL = "../docs/theme-shots";

/** Three previews per row is what fits GitHub's content column un-scrolled. */
const PREVIEW_COLUMNS = 3;

export interface GalleryEntry {
	readonly id: string;
	readonly file: string;
	readonly parsed: ParsedTheme;
}

/** Read every `themes/*.css` file and parse it, sorted by id. Throws on a malformed file (see module doc). */
export function readGalleryEntries(dir: string): GalleryEntry[] {
	return readdirSync(dir)
		.filter((f) => f.endsWith(".css"))
		.sort()
		.map((file) => {
			const css = readFileSync(join(dir, file), "utf8");
			const parsed = assertParsed(css, file);
			return { id: file.replace(/\.css$/, ""), file, parsed };
		});
}

/**
 * Build the gallery README as a string. PURE — no filesystem access — so a
 * test can import it directly and assert the committed file matches without
 * ever writing anything.
 */
export function buildGalleryReadme(entries: readonly GalleryEntry[]): string {
	const header = `# Theme gallery

This directory is a browsable gallery of ${entries.length} additional peep themes. They are not bundled with the app — each is a standalone CSS file you import.

**To use a theme:** open the command palette, choose "Import theme…", and select one of the \`.css\` files below (or paste its contents). The theme is parsed, sanitized, and added to your local theme list.

These files are also good starting points for authoring your own theme: copy one, edit the \`/*! @name … */\` frontmatter and the \`.app\` rule, and re-import.

| Theme | File | Description | Palette |
| --- | --- | --- | --- |
`;

	const rows = entries
		.map((e) => {
			const { name, description } = e.parsed.frontmatter;
			const { bg, text, accent } = e.parsed.swatch;
			return `| ${name} | [\`${e.file}\`](./${e.file}) | ${description} | \`${bg}\` \`${text}\` \`${accent}\` |`;
		})
		.join("\n");

	// Previews go in their own grid rather than a fifth table column: at a
	// legible width an image is wider than the other four columns combined, and
	// the table would degrade into one screenshot per screenful. Three per row
	// is what fits GitHub's content column without horizontal scroll.
	//
	// Only `width` is set, never `height`: the shots are full-page captures, so
	// their heights differ by theme (a newspaper masthead is multiples of
	// github-dark's h1) and pinning both would squash the tall ones. Constrain
	// one axis and let the aspect ratio carry the other.
	const previewRows = [];
	for (let i = 0; i < entries.length; i += PREVIEW_COLUMNS) {
		const chunk = entries.slice(i, i + PREVIEW_COLUMNS);
		const cells = chunk.map((e) => {
			const shot = `${SHOTS_REL}/${e.id}.png`;
			return `<a href="./${e.file}"><img src="${shot}" width="260" alt="${e.parsed.frontmatter.name} theme preview"></a><br>**${e.parsed.frontmatter.name}**`;
		});
		// Pad the final row so the table stays rectangular — GitHub renders a
		// short row by dropping cells, which visually stretches the last image.
		while (cells.length < PREVIEW_COLUMNS) cells.push("");
		previewRows.push(`| ${cells.join(" | ")} |`);
	}

	const previews = `

## Previews

Rendered from the same sample document in every theme. Regenerate with \`pnpm gen:theme-shots\`.

${`| ${new Array(PREVIEW_COLUMNS).fill(" ").join(" | ")} |`}
${`| ${new Array(PREVIEW_COLUMNS).fill(":---:").join(" | ")} |`}
${previewRows.join("\n")}`;

	const footer = `

---

GENERATED by \`scripts/generate-gallery-readme.ts\` — do not edit by hand.
Regenerate with \`pnpm gen:gallery-readme\` after adding, removing, or editing a gallery theme.
`;

	return header + rows + previews + footer;
}

const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (isMain) {
	const entries = readGalleryEntries(GALLERY_DIR);
	const readme = buildGalleryReadme(entries);
	writeFileSync(README_OUT_FILE, readme);
	console.log(`Wrote ${entries.length} gallery theme entries to ${README_OUT_FILE}`);
}
